### ISSUE TITLE
Indicating that a ServiceRequest is associated with a department

### ISSUE THREAD

**Issue by pwalsh** [govflow/govflow#26]
We've seen that some existing systems being used for 311-type requests allow "assigning" or "associating" a request with a government department, for example, "Public Works".

# Initial implementation

We want to model this, starting with a really simple use case, being, the ability to associate a ServiceRequest with a department. 

This initial implementation will support the following scenario:

- When a new service request hits the inbox, the staff users running the inbox can optionally associate a request with a department
- The StaffUser who is *assigned to* the request does not have to belong to the department - she is just a staff user who is overseeing the request in the Gov Flow dashboard, not the person actioning the fix for the request
- The department for the service request can be added/changed at any point as long as a ticket is not closed
- The view of service requests can be filtered by department (and, filtered by those not assigned to a department)

For each jurisdiction, we require:

- A list of department names

*The initial implementation essentially annotates a service request with a department from a closed list of departments for a given jurisdiction. This annotation can be used for user interface.*

Implementing this requires the following changes to the code:

- A new model / repository for "Department"
- An association between service requests and departments, where each service request can be associated with a department
- Allow, but don't require, associating a service request with a department
- If there are no departments for a given jurisdiction (i.e.: the jurisdiction does not provide one), then, don't show the department option in the UI (no server code paths need to change for this)

# Probable future use cases

All of these would require additional logic and relations not present in the initial implementation.

- Assigning tickets to staff users who belong to a department
- Direct mapping between a request's "service" and a department(s?) that handles that service
- Reassignment to new department/associated staff users
- Workflow for todo/doing/done that is department specific

**Comment by amirozer** [comment]
Looks good!

I'll add to this:
The view of service requests can be filtered by department (and, filtered by those not assigned to a department)

That we'll also allow filtering by "assigned to ____ **Department** but not assigned to any **StaffUser**" - this is the department's queue, so the department can do triage and assign their tickets to specific people

**Comment by pwalsh** [comment]
@amirozer 

> That we'll also allow filtering by "assigned to ____ Department but not assigned to any StaffUser" - this is the department's queue, so the department can do triage and assign their tickets to specific people

Great!

**Comment by idoivri** [comment]
@pwalsh minor typo: "and, filtered by those not assigned to a department" ->  "and, filtered by those not assigned to a **StaffUser**"

**Comment by pwalsh** [comment]
Implemented in https://github.com/govflow/govflow/commit/ad551c80e41f5439210036b270476b6c3417e70b
