### ISSUE TITLE
Managing communication status

### ISSUE THREAD

**Issue by pwalsh** [govflow/govflow#27]
As per https://github.com/govflow/govflow/issues/5 and specifically https://github.com/govflow/govflow/issues/5#issuecomment-991699855 we currently rely on the communication backends (Twilio and SendGrid) to manage unsubscribes, and Gov Flow is *not* aware of a given user's subscription status.

Next step around this feature would be one of:

- Manage all unsubscribe state in Gov Flow itself
- Poll those backends periodically to update our own tables with subscription state, but just as a copy of what is held by the backend service provider

I prefer the first option (less coupling with the service provider), but either should be fine. 

Needs a bit more scoping to see what is best and when we do it.

**Comment by pwalsh** [comment]
PR for doing this with email is at https://github.com/govflow/govflow/pull/61

**Comment by pwalsh** [comment]
DONE for email.

TODO for sms.

**Comment by Douglasbinha** [comment]
> As per https://github.com/govflow/govflow/issues/5 and specifically https://github.com/govflow/govflow/issues/5#issuecomment-991699855 we currently rely on the communication backends (Twilio and SendGrid) to manage unsubscribes, and Gov Flow is *not* aware of a given user's subscription status.
> 
> Next step around this feature would be one of:
> 
> - Manage all unsubscribe state in Gov Flow itself
> - Poll those backends periodically to update our own tables with subscription state, but just as a copy of what is held by the backend service provider
> 
> I prefer the first option (less coupling with the service provider), but either should be fine. 
> 
> Needs a bit more scoping to see what is best and when we do

**Comment by pwalsh** [comment]
SMS was done in https://github.com/govflow/govflow/commit/dfc6214b51863646019cedc7b8c8de1086d6f69d
