### ISSUE TITLE
Support email as an inbound channel

### ISSUE THREAD

**Issue by pwalsh** [govflow/govflow#52]
We have started with a standard webform but the goal is the support many inbound request channels.

We have a need now to support email, so, email is next!

We already depend on SendGrid for transactional email, so, we will build this feature using SendGrid's inbound parse API:

https://docs.sendgrid.com/for-developers/parsing-email/setting-up-the-inbound-parse-webhook

At a high level, this feature will require the following:

1. The GovFlow instance administrators set up all the MX config as per SendGrid, and any other SendGrid specific config
2. We expose a new endpoint on GovFlow for SendGrid to post inbound emails to.
3. Based on the domain configuration, we establish a pattern of issuing inbound email addresses per jurisdiction, and (i) for parsing association with existing requests from the inbound payload (is an issue new or further correspondence on an existing ticket), and (ii) for parsing department or service information from an inbound payload (ideally via the email name)
4. New inbound requests go to the inbox
5. Inbound requests associated with an existing request go to the comment thread of the existing request
6. Support incoming images by uploading them into the image storage

**Comment by amirozer** [comment]
Looks good!
For 3 (i) I'd consider using the subject line, with a user-friendly ticket number (related to #50). WDYT?

**Comment by pwalsh** [comment]
@amirozer 

> For 3 (i) I'd consider using the subject line, with a user-friendly ticket number (related to https://github.com/govflow/govflow/issues/50). WDYT?

Yep :)

**Comment by pwalsh** [comment]
PR https://github.com/govflow/govflow/pull/56 and commit with all changes https://github.com/govflow/govflow/commit/0700da5a96b9e52d83d1614eeb7ee0551f443d68
