### ISSUE TITLE
Preventing spam requests

### ISSUE THREAD

**Issue by pwalsh** [govflow/govflow#7]
Spam is very likely to occur very early, and I’d suggest we integrate a form of human validation from the beginning for all anonymous users (so, all users as we are not having logged in users from the beginning). That can be one of:

- reCaptcha
- hCaptcha (I’m using this in a couple of places as I prefer not to use google)
- email or phone ping (get the user to click a verify link sent via SMS or email, depending on the data she has added to the form).

The third option is the more complex, but, it also plays into our value proposition of facilitating communication between the city and citizens, and, when the requester is anonymous, that is the only way we know the details of the requester are valid (so we meet two needs - verify humanness and verify the human is contactable).

**Comment by noamoss** [comment]
(see https://github.com/govflow/govflow/discussions/58 for a focused discussion on email spam submissions)
